name: Markdown Lint

on:
  pull_request:
    branches: [main]
    paths:
      - 'outputs/*.md'

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g markdownlint-cli
      - run: markdownlint outputs/*.md
